FROM node:20

RUN apt-get update && apt-get install -y \
    chromium \
    chromium-driver \
    fonts-liberation \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libnss3 \
    libxss1 \
    libasound2 \
    xdg-utils

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV CHROME_BIN=/usr/bin/chromium

CMD ["node", "index.js"]